import { BASE_ITEMS } from "./inventory-items.js";
import { MACHINE_ITEMS } from "./machine-learning.js";
const fieldItem = (id, name, fieldAction, input) => ({
  ...BASE_ITEMS[id],
  name,
  registerable: true,
  contexts: ["field"],
  target: "field",
  actions: [{ id: "use", fieldAction, input }],
});
export const ITEMS = {
  ...BASE_ITEMS,
  ...Object.fromEntries(
    Object.entries(MACHINE_ITEMS).map(([id, machine]) => [
      id,
      { ...BASE_ITEMS[id], ...machine },
    ]),
  ),
  mach_bike: fieldItem("mach_bike", "音速自行车", "cycling", {
    mode: "mach-bike",
  }),
  acro_bike: fieldItem("acro_bike", "越野自行车", "cycling", {
    mode: "acro-bike",
  }),
  running_shoes: {
    name: "跑步鞋",
    pocket: "key",
    price: 0,
    icon: "◆",
    contexts: [],
    target: "party",
    effects: [],
    shopStock: false,
    description: "妈妈送的鞋子。按住 B / Shift 或触屏跑步键就能奔跑。",
  },
  old_rod: fieldItem("old_rod", "破旧钓竿", "fishing", { rod: "old" }),
  good_rod: fieldItem("good_rod", "好钓竿", "fishing", { rod: "good" }),
  super_rod: fieldItem("super_rod", "超级钓竿", "fishing", { rod: "super" }),
  blue_pokeblock: {
    name: "蓝色能量方块",
    price: 100,
    icon: "◆",
    contexts: ["field"],
    target: "party",
    requiresAlive: false,
    effects: [{ op: "feed", flavors: { beauty: 20 }, feel: 20 }],
    description: "干燥口味的能量方块，提高美丽度；饱食度满后不能再喂食。",
  },
  pokeball: {
    ...BASE_ITEMS.pokeball,
    shopStock: true,
    name: "精灵球",
    contexts: ["battle"],
    target: "enemy",
    effects: [{ op: "capture", bonus: 1 }],
    icon: "◉",
    purchaseRequires: { flag: "pokedex" },
    description: "捕捉野生宝可梦。降低对方体力更容易成功。",
  },
  potion: {
    ...BASE_ITEMS.potion,
    shopStock: true,
    name: "伤药",
    contexts: ["field", "battle"],
    target: "party",
    effects: [{ op: "restoreHP", amount: 20 }],
    icon: "✚",
    description: "为一只宝可梦恢复 20 点 HP。",
  },
  super_potion: {
    ...BASE_ITEMS.super_potion,
    shopStock: true,
    name: "好伤药",
    price: 700,
    icon: "✚",
    contexts: ["field", "battle"],
    target: "party",
    effects: [{ op: "restoreHP", amount: 50 }],
    description: "为一只宝可梦恢复 50 点 HP。",
  },
  antidote: {
    ...BASE_ITEMS.antidote,
    shopStock: true,
    name: "解毒药",
    price: 100,
    icon: "✚",
    contexts: ["field", "battle"],
    target: "party",
    effects: [{ op: "cureStatus", status: "poison" }],
    description: "解除一只宝可梦的中毒状态。",
  },
  great_ball: {
    ...BASE_ITEMS.great_ball,
    shopStock: true,
    name: "超级球",
    price: 600,
    icon: "◉",
    contexts: ["battle"],
    target: "enemy",
    effects: [{ op: "capture", bonus: 1.5 }],
    purchaseRequires: { flag: "pokedex" },
    description: "比精灵球更容易捕捉野生宝可梦。",
  },
};
