"""Export fixed-reference region-map cells, bindings and original cursor/player art."""
import argparse
import hashlib
import io
import json
from pathlib import Path
import re
import subprocess
from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
REVISION = '731ad5bfd6e6f265508d0efcca0ba42f9dcf5881'
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--source', type=Path, default=ROOT / 'work/pokeemerald')
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
if subprocess.check_output(['git', '-C', str(args.source), 'rev-parse', 'HEAD'], text=True).strip() != REVISION:
    raise ValueError('Region map requires the pinned read-only reference')
inputs = {}
def read(relative):
    data = (args.source / relative).read_bytes()
    inputs[relative] = hashlib.sha256(data).hexdigest()
    return data
sections = json.loads(read('src/data/region_map/region_map_sections.json'))['map_sections']
layout = read('src/data/region_map/region_map_layout.h').decode()
cells = [re.findall(r'MAPSEC_\w+', row) for row in re.findall(r'\{([^{}]+)\}', layout)]
if len(cells) != 15 or any(len(row) != 28 for row in cells):
    raise ValueError('Unexpected native region grid')
source = read('src/region_map.c').decode()
block = source[source.index('static const mapsec_u16_t sRegionMap_SpecialPlaceLocations'):]
block = block[:block.index('};')]
aliases = dict(re.findall(r'\{(MAPSEC_\w+),\s*(MAPSEC_\w+)\}', block))
bindings = {}
for path in sorted((args.source / 'data/maps').glob('*/map.json')):
    entry = json.loads(read(path.relative_to(args.source).as_posix()))
    bindings[path.parent.name] = entry.get('region_map_section')
content = {'width': 28, 'height': 15, 'cells': [None if c == 'MAPSEC_NONE' else c for row in cells for c in row],
           'sections': {s['id']: s for s in sections}, 'bindings': bindings, 'aliases': aliases}
outputs = {ROOT / 'generated/packs/emerald/region-map-data.js':
           ('// @generated by tools/ui/export-region-map.py; do not edit.\nexport const EMERALD_REGION_MAP = ' + json.dumps(content, ensure_ascii=False, indent=2) + ';\n').encode()}
for name, asset in [('cursor', 'cursor_small'), ('player-male', 'brendan_icon'), ('player-female', 'may_icon')]:
    indexed = Image.open(io.BytesIO(read(f'graphics/pokenav/region_map/{asset}.png')))
    raw = indexed.getpalette()
    colors = [tuple(raw[i:i+3]) for i in range(0, len(raw), 3)]
    if name == 'cursor':
        colors = [tuple(map(int, line.split())) for line in read('graphics/pokenav/region_map/cursor.pal').decode().splitlines()[3:] if line.strip()]
    image = Image.new('RGBA', indexed.size)
    image.putdata([(*colors[v], 0 if v == 0 else 255) for v in indexed.getdata()])
    data = io.BytesIO(); image.save(data, format='PNG')
    outputs[ROOT / f'generated/assets/ui/region-{name}.png'] = data.getvalue()
manifest = {'source': 'pret/pokeemerald', 'revision': REVISION, 'inputs': inputs,
            'outputs': {p.relative_to(ROOT).as_posix(): hashlib.sha256(data).hexdigest() for p, data in outputs.items()}}
outputs[ROOT / 'generated/packs/emerald/region-map-source.json'] = (json.dumps(manifest, indent=2) + '\n').encode()
changed = []
for path, data in outputs.items():
    if not path.exists() or path.read_bytes() != data:
        changed.append(path.relative_to(ROOT).as_posix())
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True); path.write_bytes(data)
print(json.dumps({'check': args.check, 'files': changed}, indent=2))
