"""Export separate original Birch, naming backgrounds and portraits; no baked scene or reference writes."""
import argparse
import hashlib
import io
import json
from pathlib import Path
import struct
import subprocess
from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
REVISION = '731ad5bfd6e6f265508d0efcca0ba42f9dcf5881'
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--source', type=Path, default=ROOT / 'work/pokeemerald')
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
if subprocess.check_output(['git', '-C', str(args.source), 'rev-parse', 'HEAD'], text=True).strip() != REVISION:
    raise ValueError('Pinned original reference required')
inputs, outputs, resources = {}, {}, {}


def read(path):
    data = (args.source / path).read_bytes()
    inputs[path] = hashlib.sha256(data).hexdigest()
    return data


def palette(path):
    return [tuple(map(int, line.split())) for line in read(path).decode().splitlines()[3:] if line.strip()]


def indexed(path):
    return Image.open(io.BytesIO(read(path)))


def add(name, image):
    path = ROOT / f'generated/assets/ui/new-game-{name}.png'
    data = io.BytesIO()
    image.save(data, format='PNG')
    outputs[path] = data.getvalue()
    resources['new-game-' + name] = path.relative_to(ROOT).as_posix()


def sprite(path, pal=None):
    im = indexed(path)
    raw = im.getpalette()
    pal = pal or [tuple(raw[i:i+3]) for i in range(0, len(raw), 3)]
    result = Image.new('RGBA', im.size)
    result.putdata([(*pal[v], 0 if v == 0 else 255) for v in im.getdata()])
    return result


def tiled(tiles, tilemap, pal, transparent=False):
    im = indexed(tiles)
    data = read(tilemap)
    entries = struct.unpack('<' + 'H' * (len(data) // 2), data)
    result = Image.new('RGBA', (256, 160))
    for y in range(20):
        for x in range(32):
            e = entries[y * 32 + x]
            index, bank = e & 1023, e >> 12
            if index >= im.width * im.height // 64:
                raise ValueError('Tile outside original sheet')
            tile = im.crop(((index % (im.width // 8)) * 8, (index // (im.width // 8)) * 8,
                            (index % (im.width // 8)) * 8 + 8, (index // (im.width // 8)) * 8 + 8))
            out = Image.new('RGBA', (8, 8))
            colors = [bank * 16 + v for v in tile.getdata()]
            if max(colors) >= len(pal):
                raise ValueError('Palette outside source')
            out.putdata([(*pal[v], 0 if transparent and v % 16 == 0 else 255) for v in colors])
            if e & 1024: out = out.transpose(Image.Transpose.FLIP_LEFT_RIGHT)
            if e & 2048: out = out.transpose(Image.Transpose.FLIP_TOP_BOTTOM)
            result.paste(out, (x * 8, y * 8))
    return result


read('src/main_menu.c'); read('data/text/birch_speech.inc'); read('src/naming_screen.c'); read('src/data/object_events/object_event_graphics_info.h')
read('src/pokeball.c'); read('src/pokemon_animation.c'); read('src/pokemon.c'); read('src/strings.c'); read('src/data/pokemon_graphics/front_pic_anims.h'); read('src/sprite.c')
outputs[ROOT / 'generated/assets/audio/cry-lotad.wav'] = read('sound/direct_sound_samples/cries/lotad.wav')
base = palette('graphics/birch_speech/bg0.pal') + palette('graphics/birch_speech/bg1.pal')
gradient = palette('graphics/birch_speech/bg2.pal')
sheet = Image.new('RGBA', (256, 160 * 9))
for stage in range(9):
    colors = base[:]
    colors[1:9] = gradient[stage:stage+8]
    sheet.paste(tiled('graphics/birch_speech/shadow.png', 'graphics/birch_speech/map.bin', colors), (0, stage * 160))
add('platform', sheet)
add('birch', sprite('graphics/birch_speech/birch.png'))
add('male', sprite('graphics/trainers/front_pics/brendan.png', palette('graphics/trainers/palettes/brendan.pal')))
add('female', sprite('graphics/trainers/front_pics/may.png', palette('graphics/trainers/palettes/may.pal')))
add('lotad', sprite('graphics/pokemon/lotad/anim_front.png', palette('graphics/pokemon/lotad/normal.pal')))
menu = palette('graphics/naming_screen/menu.pal')
keyboard = palette('graphics/naming_screen/keyboard.pal')
colors = [(0, 0, 0)] * 256
colors[:len(menu)] = menu
colors[160:176] = keyboard
add('naming', tiled('graphics/naming_screen/menu.png', 'graphics/naming_screen/background.bin', colors))
for gender, actor in [('male', 'brendan'), ('female', 'may')]:
    add('icon-' + gender, sprite(f'graphics/object_events/pics/people/{actor}/walking.png', palette(f'graphics/object_events/palettes/{actor}.pal')).crop((0, 0, 16, 32)))
meta = ROOT / 'generated/packs/emerald/new-game-art.js'
outputs[meta] = ('// @generated by tools/ui/export-new-game.py\nexport const NEW_GAME_RESOURCES = ' + json.dumps(resources, indent=2) + ';\n').encode()
manifest = {'source': 'pret/pokeemerald', 'revision': REVISION, 'inputs': inputs,
            'outputs': {p.relative_to(ROOT).as_posix(): hashlib.sha256(data).hexdigest() for p, data in outputs.items()}}
outputs[ROOT / 'generated/packs/emerald/new-game-source.json'] = (json.dumps(manifest, indent=2) + '\n').encode()
changed = []
for path, data in outputs.items():
    if not path.exists() or path.read_bytes() != data:
        changed.append(path.relative_to(ROOT).as_posix())
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
print(json.dumps({'check': args.check, 'files': changed}, indent=2))
