"""Pinned indexed graphics extraction. Each layer remains a separate resource."""
import hashlib
import io
import json
from pathlib import Path
import struct
import subprocess
from PIL import Image

REVISION = '731ad5bfd6e6f265508d0efcca0ba42f9dcf5881'


class NativeArt:
    def __init__(self, source, root, prefix):
        if subprocess.check_output(['git', '-C', str(source), 'rev-parse', 'HEAD'], text=True).strip() != REVISION:
            raise ValueError('Pinned reference required')
        self.source, self.root, self.prefix = source, root, prefix
        self.inputs, self.outputs, self.resources = {}, {}, {}

    def read(self, path):
        data = (self.source / path).read_bytes()
        self.inputs[path] = hashlib.sha256(data).hexdigest()
        return data

    def indexed(self, path):
        return Image.open(io.BytesIO(self.read(path)))

    def palette(self, path):
        if path.endswith('.png'):
            raw = self.indexed(path).getpalette()
            return [tuple(raw[i:i+3]) for i in range(0, len(raw), 3)]
        return [tuple(map(int, line.split())) for line in self.read(path).decode().splitlines()[3:] if line.strip()]

    def tilemap(self, tiles, tilemap, colors, size=(256, 256), affine=False, transparent=True, tail=None):
        im, data = self.indexed(tiles), self.read(tilemap)
        if tail:
            # Earlier 8bpp VRAM remains beyond the later 4bpp load. Compile that explicit texture tail.
            prior = self.indexed(tail)
            raw = []
            for i in range(prior.width * prior.height // 64): raw.extend(self.raw_tiles(prior, i, 8, 8).getdata())
            count = len(raw) // 32
            filled = Image.new('P', (128, ((count + 15) // 16) * 8))
            filled.paste(im, (0, 0))
            for i in range(im.width * im.height // 64, count):
                tile = Image.new('P', (8, 8))
                tile.putdata([n for byte in raw[i*32:(i+1)*32] for n in (byte & 15, byte >> 4)])
                filled.paste(tile, (i % 16 * 8, i // 16 * 8))
            im = filled
        entries = data if affine else struct.unpack('<' + 'H' * (len(data) // 2), data)
        cols, rows = size[0] // 8, size[1] // 8
        if affine and len(entries) >= cols * rows:
            entries = entries[:cols * rows]
        if len(entries) != cols * rows:
            raise ValueError(f'Tilemap size mismatch: {tilemap}')
        result = Image.new('RGBA', size)
        for y in range(rows):
            for x in range(cols):
                # Text maps consist of 32x32 screen blocks, affine maps are linear bytes.
                slot = y * cols + x if affine else ((y // 32) * (cols // 32) + x // 32) * 1024 + (y % 32) * 32 + x % 32
                e = entries[slot]
                index, bank = (e, 0) if affine else (e & 1023, e >> 12)
                tile = self.raw_tiles(im, index, 8, 8)
                out = Image.new('RGBA', (8, 8))
                out.putdata([(*colors[bank * 16 + v], 0 if transparent and v == 0 else 255) for v in tile.getdata()])
                if not affine and e & 1024: out = out.transpose(Image.Transpose.FLIP_LEFT_RIGHT)
                if not affine and e & 2048: out = out.transpose(Image.Transpose.FLIP_TOP_BOTTOM)
                result.paste(out, (x * 8, y * 8))
        return result

    @staticmethod
    def raw_tiles(image, offset, width, height):
        out = Image.new('P', (width, height))
        columns = image.width // 8
        for t in range(width * height // 64):
            i = offset + t
            if i >= columns * (image.height // 8):
                raise ValueError('Sprite tiles outside original sheet')
            tile = image.crop((i % columns * 8, i // columns * 8, i % columns * 8 + 8, i // columns * 8 + 8))
            out.paste(tile, (t % (width // 8) * 8, t // (width // 8) * 8))
        return out

    def sprite(self, path, offsets, size, colors=None):
        image = self.indexed(path)
        colors = colors or self.palette(path)
        sheet = Image.new('RGBA', (size[0], size[1] * len(offsets)))
        for frame, offset in enumerate(offsets):
            raw = self.raw_tiles(image, offset, *size)
            out = Image.new('RGBA', size)
            out.putdata([(*colors[v], 0 if v == 0 else 255) for v in raw.getdata()])
            sheet.paste(out, (0, frame * size[1]))
        return sheet

    def add(self, name, image):
        path = self.root / f'generated/assets/ui/{self.prefix}-{name}.png'
        buffer = io.BytesIO(); image.save(buffer, format='PNG')
        self.outputs[path] = buffer.getvalue()
        self.resources[self.prefix + '-' + name] = path.relative_to(self.root).as_posix()

    def finish(self, module, exports, check=False):
        path = self.root / f'generated/packs/emerald/{module}-art.js'
        self.outputs[path] = ('// @generated by tools/ui/export-' + module + '.py\n' + '\n'.join(
            f'export const {key} = {json.dumps(value, indent=2)};' for key, value in exports.items()) + '\n').encode()
        manifest = {'source': 'pret/pokeemerald', 'revision': REVISION, 'inputs': self.inputs,
                    'outputs': {p.relative_to(self.root).as_posix(): hashlib.sha256(data).hexdigest() for p, data in self.outputs.items()}}
        self.outputs[self.root / f'generated/packs/emerald/{module}-source.json'] = (json.dumps(manifest, indent=2) + '\n').encode()
        changed = []
        for path, data in self.outputs.items():
            if not path.exists() or path.read_bytes() != data:
                changed.append(path.relative_to(self.root).as_posix())
                if not check:
                    path.parent.mkdir(parents=True, exist_ok=True); path.write_bytes(data)
        print(json.dumps({'check': check, 'files': changed}))
        return bool(changed)
