// @generated by tools/audio/render-bgm.py; regenerate from source/config.
export const bgmPlugin = {
  ...{"id": "emerald-first-bgm", "apiVersion": 1, "version": "1.0.0", "dataVersion": 1, "permissions": []},
  setup(api) { api.presentation.audio("mus_littleroot", {"kind": "music", "source": "assets/audio/emerald-first-bgm/mus_littleroot.wav", "volume": 0.6, "loop": true, "loopStart": 54.16662131519274, "loopEnd": 107.49990929705216, "fadeInMs": 0, "fadeOutMs": 0}); },
};
