"""Install one consolidated game audio pack: all rendered songs and sounds behind a single plugin.

Per-track rendering stays in render-bgm.py. This owner merges already rendered track packs into
the installed layout so the game ships one asset directory, one plugin module and one manifest.
"""
import argparse
import hashlib
import json
import os
import shutil
import tempfile
from pathlib import Path

PROJECT = Path(__file__).resolve().parent.parent.parent
SOUND_SECTIONS = ('music', 'sounds')


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def load_track_packs(build):
    """Index rendered track packs by their original song identity."""
    result = {}
    for folder in sorted(build.iterdir()):
        manifest = folder / 'manifest.json'
        if folder.is_dir() and manifest.is_file():
            data = json.loads(manifest.read_text())
            result[data['song']] = (folder, data)
    return result


def resolve_cue(track_id, song, kind, section, folder, data):
    """The installed cue keeps the original identity: owner:mus_song or owner:se_song."""
    local = song.lower()
    asset = f'assets/audio/{track_id}/{section}/{local}.wav'
    cue = dict(data['cue'])
    cue['source'] = asset
    cue['kind'] = kind
    if kind == 'music':
        cue.update({'loop': True,
                    'loopStart': data['cue']['loopStart'],
                    'loopEnd': data['cue']['loopEnd']})
    else:
        for key in ('loopStart', 'loopEnd'):
            cue.pop(key, None)
        cue['loop'] = False
    return local, asset, cue


def install(pack_file, build, project, check=False):
    spec = json.loads(pack_file.read_text())
    track_id = spec['id']
    if not track_id or any(c not in 'abcdefghijklmnopqrstuvwxyz0123456789-' for c in track_id):
        raise ValueError('Invalid audio pack identity')
    available = load_track_packs(build)
    root = project.resolve() / 'dist'
    changes, tracks, superseded, removals = {}, [], set(), []
    for section, kind in zip(SOUND_SECTIONS, ('music', 'sound')):
        for entry in spec.get(section) or []:
            song = entry['song']
            if song not in available:
                raise ValueError(f'Missing rendered track pack for {song}; render it before installing')
            folder, data = available[song]
            if data.get('sourceRevision') != spec['sourceRevision']:
                raise ValueError(f'Reference revision differs for {song}')
            if data.get('renderer', {}).get('revision') != spec['rendererRevision']:
                raise ValueError(f'Renderer revision differs for {song}')
            local, asset, cue = resolve_cue(track_id, song, kind, section, folder, data)
            audio = folder / data['assetName']
            if digest(audio) != data['assetSha256']:
                raise ValueError(f'Track checksum differs from its manifest: {song}')
            if not asset.startswith(f'assets/audio/{track_id}/'):
                raise ValueError('Invalid consolidated asset destination')
            changes[(root / asset).resolve()] = audio.read_bytes()
            tracks.append({
                'song': song,
                'kind': kind,
                'selection': entry.get('selection', 'map-music' if kind == 'music' else 'ui'),
                'title': entry.get('title', data.get('renderConfig', {}).get('title', song)),
                'config': entry.get('config'),
                'cueId': f'{track_id}:{local}',
                'source': asset,
                'cue': cue,
                'assetSha256': data['assetSha256'],
                'frames': data['frames'],
                'durationSeconds': data['durationSeconds'],
                'midiLoopStartFrame': data['midiLoopStartFrame'],
                'midiLoopEndFrame': data['midiLoopEndFrame'],
                'renderConfig': data.get('renderConfig'),
                'renderer': data.get('renderer'),
                'inputs': data.get('inputs', []),
            })
            superseded.add(data['id'])
    if not tracks:
        raise ValueError('Audio pack declares no tracks; nothing to install')
    # One plugin registers every cue; the runtime keeps choosing by original identity.
    plugin = {'id': track_id, 'apiVersion': 1, 'version': '1.0.0', 'dataVersion': 1, 'permissions': []}
    lines = ['// @generated by tools/audio/bundle-audio.py; regenerate from source/config.',
             'export const audioPlugin = {', '  ...' + json.dumps(plugin, ensure_ascii=False) + ',',
             '  setup(api) {']
    for track in tracks:
        local = track['cueId'].split(':', 1)[1]
        lines.append(f'    api.presentation.audio({json.dumps(local)}, '
                     f'{json.dumps(track["cue"], ensure_ascii=False)});')
    lines += ['  },', '};', '']
    module = root / 'plugins' / f'{track_id}.js'
    changes[module] = ('\n'.join(lines)).encode()
    catalog_path = root / 'plugins/catalog.json'
    catalog = json.loads(catalog_path.read_text())
    kept, removed = [], []
    for entry in catalog['plugins']:
        if entry.get('export') == 'bgmPlugin' and entry['id'] in superseded:
            removed.append(entry['id'])
            stale_module = root / 'plugins' / f"{entry['id']}.js"
            if stale_module.is_file():
                removals.append(stale_module)
        elif entry['id'] == track_id:
            kept.append({**entry, 'module': f'./{track_id}.js', 'export': 'audioPlugin',
                         'enabled': bool(spec.get('defaultEnabled', True)) or entry.get('enabled', False)})
        else:
            kept.append(entry)
    if not any(e['id'] == track_id for e in kept):
        kept.append({'id': track_id, 'module': f'./{track_id}.js', 'export': 'audioPlugin',
                     'enabled': bool(spec.get('defaultEnabled', True))})
    changes[catalog_path] = (json.dumps({'version': catalog.get('version', 1), 'plugins': kept},
                                        ensure_ascii=False, indent=2) + '\n').encode()
    # Superseded per-track modules stay removed even if a later run no longer sees them in the catalog.
    for old in sorted(superseded):
        stale_module = root / 'plugins' / f'{old}.js'
        if stale_module.is_file() and stale_module not in removals:
            removals.append(stale_module)
    manifest = {
        'id': track_id, 'title': spec['title'], 'defaultEnabled': bool(spec.get('defaultEnabled', True)),
        'sourceRevision': spec['sourceRevision'], 'rendererRevision': spec['rendererRevision'],
        'cuePrefix': track_id, 'tracks': tracks,
        'supersededPacks': sorted(superseded),
        'verification': {'installed': True, 'referenceListening': 'pending', 'inGameListening': 'pending'},
        'fidelity': 'Source MIDI and original voicegroups/samples via m4a emulation; not verified bit-exact hardware output.',
    }
    manifest_path = root / 'assets' / 'audio' / track_id / 'manifest.json'
    changes[manifest_path] = (json.dumps(manifest, ensure_ascii=False, indent=2) + '\n').encode()
    # Drop the per-track asset directories this consolidated pack replaces.
    for old in sorted(superseded):
        stale = root / 'assets' / 'audio' / old
        if stale.is_dir():
            removals.append(stale)
    written = {}
    for path, content in changes.items():
        if content is not None and (not path.exists() or path.read_bytes() != content):
            written[path] = content
    removals = [p for p in dict.fromkeys(removals) if p.exists()]
    report = {'pack': track_id, 'tracks': [t['song'] for t in tracks],
              'cues': [t['cueId'] for t in tracks],
              'superseded': sorted(superseded), 'removedPlugins': removed,
              'files': sorted(str(p.relative_to(project.resolve())) for p in written),
              'removed': sorted(str(p.relative_to(project.resolve())) for p in removals),
              'check': check}
    if not check:
        before = {p: (p.read_bytes() if p.is_file() else None) for p in written}
        removed_bytes = {p: p.read_bytes() for p in removals if p.is_file()}
        committed = []
        with tempfile.TemporaryDirectory(dir=project, prefix='.audio-install-') as staging:
            staged = []
            for i, (path, content) in enumerate(written.items()):
                temp = Path(staging) / str(i)
                temp.write_bytes(content)
                staged.append((path, temp))
            try:
                for path, temp in staged:
                    path.parent.mkdir(parents=True, exist_ok=True)
                    os.replace(temp, path)
                    committed.append(path)
                for path in removals:
                    if path.is_dir():
                        shutil.rmtree(path)
                    else:
                        path.unlink()
            except BaseException:
                for path in reversed(committed):
                    if before[path] is None:
                        if path.is_dir():
                            shutil.rmtree(path)
                        elif path.exists():
                            path.unlink()
                    else:
                        path.write_bytes(before[path])
                for path, content in removed_bytes.items():
                    path.parent.mkdir(parents=True, exist_ok=True)
                    path.write_bytes(content)
                raise
    return report


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--pack', type=Path, default=Path(__file__).resolve().parent / 'pack.json')
    parser.add_argument('--build', type=Path, required=True,
                        help='Directory holding the rendered per-track packs')
    parser.add_argument('--project', type=Path, default=PROJECT)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    print(json.dumps(install(args.pack.resolve(), args.build.resolve(), args.project.resolve(), args.check),
                     ensure_ascii=False, indent=2))
