"""Export gapless MP3 delivery assets from retained WAV sources; never rewrite a source."""
import argparse
from concurrent.futures import ThreadPoolExecutor
import hashlib
import json
import os
from pathlib import Path
import subprocess
import tempfile
import wave

ROOT = Path(__file__).resolve().parents[2]
MANIFEST = Path('generated/packs/emerald/audio-delivery.json')
MODULE = Path('generated/packs/emerald/audio-delivery.js')
RATE = 44100
BITRATE = 128000
MP3_FRAME = 1152


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def sources(root):
    directory = root / 'generated/assets/audio'
    if directory.is_symlink():
        raise ValueError('Audio source directory cannot be a symlink')
    result = sorted(directory.rglob('*.wav'))
    if not result:
        raise ValueError('No WAV source assets')
    for path in result:
        if any(parent.is_symlink() for parent in [path, *path.parents] if parent.is_relative_to(root)):
            raise ValueError('Audio source cannot contain symlinks')
    return result


def source_record(root, path):
    with wave.open(str(path)) as audio:
        if audio.getnchannels() not in (1, 2) or audio.getcomptype() != 'NONE':
            raise ValueError('Expected mono/stereo PCM WAV')
        return {'source': path.relative_to(root).as_posix(), 'sourceSha256': sha(path),
                'sourceBytes': path.stat().st_size, 'sourceRate': audio.getframerate(),
                'sourceFrames': audio.getnframes(), 'channels': audio.getnchannels()}


def decoded_frames(path, channels, ffmpeg):
    result = subprocess.run([ffmpeg, '-nostdin', '-v', 'error', '-i', str(path),
                             '-ar', str(RATE), '-ac', str(channels), '-f', 's16le', '-'],
                            capture_output=True, check=True)
    return len(result.stdout) // (2 * channels)


def validate_frames(frames, record):
    # Some MP3 decoders retain part of the final padded frame. Never truncate PCM;
    # loop boundaries stay at the original seconds, before this trailing padding.
    expected = record['sourceFrames'] * RATE / record['sourceRate']
    if frames < expected - 1 or frames > expected + MP3_FRAME:
        raise ValueError(f'Compressed duration changed: {record["source"]}')


def module_bytes(tracks):
    mapping = {track['source']: track['output'] for track in tracks}
    return ('// @generated by tools/audio/compress-audio.py; WAV sources remain offline.\n'
            'export const AUDIO_DELIVERY_SOURCES = Object.freeze(' +
            json.dumps(mapping, indent=2, sort_keys=True) + ');\n').encode()


def commit(changes):
    """Install only staged owned outputs; restore existing outputs on an interrupted write."""
    before, completed, staged = {}, [], {}
    for path in changes:
        if path.is_symlink() or any(parent.is_symlink() for parent in path.parents):
            raise ValueError('Delivery output cannot contain symlinks')
    try:
        for path, content in changes.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            before[path] = path.read_bytes() if path.exists() else None
            # Stage next to the destination so replacement also works across filesystems.
            with tempfile.NamedTemporaryFile(dir=path.parent, delete=False) as file:
                file.write(content)
                staged[path] = Path(file.name)
        for path, temporary in staged.items():
            os.replace(temporary, path)
            completed.append(path)
    except BaseException:
        for path in reversed(completed):
            if before[path] is None:
                path.unlink()
            else:
                path.write_bytes(before[path])
        raise
    finally:
        for temporary in staged.values():
            temporary.unlink(missing_ok=True)


def export(root, ffmpeg='ffmpeg'):
    root = Path(root).resolve()
    inputs = sources(root)
    with tempfile.TemporaryDirectory(prefix='emerald-audio-encode-') as temp:
        def encode(path):
            record = source_record(root, path)
            target = path.with_suffix('.mp3')
            temporary = Path(temp) / (record['source'].replace('/', '_') + '.mp3')
            subprocess.run([ffmpeg, '-nostdin', '-v', 'error', '-i', str(path),
                            '-map_metadata', '-1', '-ar', str(RATE), '-c:a', 'libmp3lame',
                            '-b:a', str(BITRATE), '-write_xing', '1', '-y', str(temporary)],
                           capture_output=True, check=True)
            frames = decoded_frames(temporary, record['channels'], ffmpeg)
            validate_frames(frames, record)
            record.update({'output': target.relative_to(root).as_posix(),
                           'outputSha256': sha(temporary), 'outputBytes': temporary.stat().st_size,
                           'decodedRate': RATE, 'decodedFrames': frames})
            return record, target, temporary.read_bytes()
        with ThreadPoolExecutor(max_workers=3) as pool:
            encoded = list(pool.map(encode, inputs))
        # A concurrently edited source cannot produce a misleading provenance record.
        for record, _, _ in encoded:
            if sha(root / record['source']) != record['sourceSha256']:
                raise ValueError('WAV source changed during compression')
        tracks = [record for record, _, _ in encoded]
        manifest = {'version': 1, 'codec': 'mp3', 'bitrate': BITRATE,
                    'generator': 'tools/audio/compress-audio.py', 'tracks': tracks}
        changes = {target: content for _, target, content in encoded}
        changes[root / MANIFEST] = (json.dumps(manifest, indent=2) + '\n').encode()
        changes[root / MODULE] = module_bytes(tracks)
        commit(changes)
    return report(manifest)


def verify(root, ffmpeg='ffmpeg'):
    root = Path(root).resolve()
    manifest = json.loads((root / MANIFEST).read_text())
    if manifest['version'] != 1 or manifest['codec'] != 'mp3' or manifest['bitrate'] != BITRATE:
        raise ValueError('Unexpected delivery format')
    tracks = manifest['tracks']
    expected_sources = {path.relative_to(root).as_posix() for path in sources(root)}
    if {record['source'] for record in tracks} != expected_sources or len(tracks) != len(expected_sources):
        raise ValueError('Delivery manifest is stale or contains duplicate sources')
    for record in tracks:
        source = root / record['source']
        actual = source_record(root, source)
        if any(actual[key] != record[key] for key in actual):
            raise ValueError(f'Stale audio source: {record["source"]}')
        output = source.with_suffix('.mp3')
        if record['output'] != output.relative_to(root).as_posix() or output.is_symlink():
            raise ValueError('Unexpected delivery destination')
        if sha(output) != record['outputSha256'] or output.stat().st_size != record['outputBytes']:
            raise ValueError(f'Corrupt compressed audio: {record["output"]}')
        frames = decoded_frames(output, record['channels'], ffmpeg)
        if record['decodedRate'] != RATE:
            raise ValueError('Compressed duration differs from PCM source')
        # Decoder versions can trim final MP3 padding differently. Both the recorded
        # observation and this decoder must retain the source interval, not match padding.
        validate_frames(record['decodedFrames'], record)
        validate_frames(frames, record)
    if (root / MODULE).read_bytes() != module_bytes(tracks):
        raise ValueError('Runtime audio mapping is stale')
    return report(manifest)


def report(manifest):
    tracks = manifest['tracks']
    return {'files': len(tracks), 'sourceBytes': sum(t['sourceBytes'] for t in tracks),
            'deliveryBytes': sum(t['outputBytes'] for t in tracks)}


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--project', type=Path, default=ROOT)
    parser.add_argument('--ffmpeg', default='ffmpeg')
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    print(json.dumps((verify if args.check else export)(args.project, args.ffmpeg)))
