# -*- coding: utf-8 -*-
"""Generate original cycling permissions from read-only map headers."""
import json
from pathlib import Path
root = Path(__file__).resolve().parents[1]
data = {}
for path in sorted((root / "work/pokeemerald/data/maps").glob("*/map.json")):
    header = json.loads(path.read_text())
    data[header["name"]] = header["allow_cycling"]
(root / "dist/engine/rules/gen3/map-cycling.js").write_text(
    "// Generated by tools/import-map-cycling.py; read-only reference 731ad5bfd6e6f265508d0efcca0ba42f9dcf5881.\n"
    "// Header metadata does not imply playable maps.\nexport const GEN3_MAP_CYCLING = " + json.dumps(data, indent=2) + ";\n")
print(f"{len(data)} map cycling permissions")
