"""Import TM/HM order and species eligibility; reference tree stays read-only."""
import json
import re
import subprocess
from pathlib import Path

root = Path('work/pokeemerald')
source = (root / 'include/constants/tms_hms.h').read_text()
parts = source.split('#define FOREACH_HM(F)')
tms = re.findall(r'F\((\w+)\)', parts[0])
hms = re.findall(r'F\((\w+)\)', parts[1].split('#define FOREACH_TMHM')[0])
assert len(tms) == 50 and len(hms) == 8
learnsets = {}
for species, body in re.findall(r'\[SPECIES_(\w+)\]\s*=\s*\{\s*\.learnset\s*=\s*\{(.*?)\}\s*\}', (root / 'src/data/pokemon/tmhm_learnsets.h').read_text(), re.S):
    learnsets[species.lower()] = [move.lower() for move in re.findall(r'\.(\w+)\s*=\s*TRUE', body)]
machines = {}
for kind, moves in [('tm', tms), ('hm', hms)]:
    for number, move in enumerate(moves, 1):
        key = kind + '_' + move.lower()
        machines[key] = {'move': move.lower(), 'number': number, 'kind': kind, 'consume': int(kind == 'tm'), 'protected': kind == 'hm'}
metadata = {'revision': subprocess.check_output(['git', '-C', str(root), 'rev-parse', 'HEAD'], text=True).strip(), 'sources': ['include/constants/tms_hms.h', 'src/data/pokemon/tmhm_learnsets.h', 'src/party_menu.c', 'src/pokemon.c', 'src/pokemon_summary_screen.c']}
Path('dist/engine/rules/gen3/machine-learning.js').write_text('// Generated by tools/import-machine-learning.py; do not edit derived data.\nexport const MACHINE_SOURCE = ' + json.dumps(metadata, indent=2) + ';\nexport const MACHINES = ' + json.dumps(machines, indent=2) + ';\nexport const MACHINE_LEARNSETS = ' + json.dumps(learnsets, indent=2) + ';\n')
print(f'{len(machines)} machines, {len(learnsets)} species learnsets')
