"""Import actual native anim_front sheets, not front.png's reserved black VRAM frames.

Run: python3 tools/import.py detail-sprites [SOURCE] [--species ID...] [--check]
Frame timing remains pack policy; native animation task scripts are not interpreted here.
"""
import argparse
import hashlib
import json
import re
from PIL import Image
from imports.context import ImportSession, arguments, source_argument
from imports.pixel_assets import paint_4bpp, icon_palette_path, read_palette

parser = argparse.ArgumentParser(description=__doc__)
source_argument(parser)
args = arguments(parser, selectors=('species',))
session = ImportSession(args, 'import-detail-sprites.py')
content = session.load()
metadata = session.dist / 'packs/emerald/detail-sprite-frames.js'
provenance_path = session.dist / 'assets/detail-sprite-source.json'
provenance = json.loads(provenance_path.read_text()) if provenance_path.exists() else {'inputs': {}}
# Partial imports preserve the other species' frame metadata.
clips = dict((key, int(count)) for key, count in re.findall(r'^  (\w+): (\d+),$', metadata.read_text(), re.M)) if metadata.exists() else {}
for species in sorted(session.select('species', content['species'])):
    folder = session.source / 'graphics/pokemon' / species
    source = folder / 'anim_front.png'
    if not source.exists():
        source = folder / 'front.png'
    palette_path = folder / 'normal.pal'
    palette = [tuple(map(int, line.split())) for line in palette_path.read_text().splitlines()[3:19]]
    with Image.open(source) as indexed:
        if indexed.width != 64 or indexed.height % 64:
            raise ValueError(f'Expected 64px vertical animation sheet: {source}')
        # Static front art can contain reserved slots; only its first sprite is used.
        painted = paint_4bpp(indexed if source.name == 'anim_front.png' else indexed.crop((0, 0, 64, 64)), palette, transparent=True)
    clips[species] = painted.height // 64
    for index in range(clips[species]):
        frame = painted.crop((0, index * 64, 64, (index + 1) * 64))
        alpha = frame.getchannel('A')
        if alpha.getextrema() != (0, 255) or not alpha.getbbox():
            raise ValueError(f'Invalid detail frame (no transparent background or foreground): {species}/{index}')
    session.image(painted, session.dist / f'assets/{species}-detail.png')
    icon_source = folder / 'icon.png'
    icon_palette = icon_palette_path(session.source, species)
    with Image.open(icon_source) as indexed:
        session.image(paint_4bpp(indexed, read_palette(icon_palette), transparent=True), session.dist / f'assets/{species}-icon.png')
    for path in (source, palette_path, icon_source, icon_palette,
                 session.source / 'src/pokemon_icon.c', session.source / 'src/graphics.c'):
        provenance['inputs'][str(path.relative_to(session.source))] = hashlib.sha256(path.read_bytes()).hexdigest()
session.text(metadata, '// @generated by tools/imports/commands/dex/import-detail-sprites.py; actual anim_front frames, timing defined by the pack.\n'
             + 'export const DETAIL_SPRITE_FRAMES = Object.freeze({\n'
             + ''.join(f'  {key}: {count},\n' for key, count in sorted(clips.items())) + '});\n')
session.text(provenance_path, json.dumps(provenance, indent=2) + "\n")
print(f'Detail frames: {len(clips)} species, {sum(n > 1 for n in clips.values())} animation sheets.')
session.finish()
