"""Describe existing PNG frames without modifying readonly reference files or image resources.

Run from any directory: python3 tools/import.py detail-sprites
Generated timing is a project demonstration policy (125 ms/frame), not original animation scripts.
"""
import json
import struct
from pathlib import Path
from imports.context import PROJECT, ImportSession, arguments
import argparse
parser = argparse.ArgumentParser()
args = arguments(parser, selectors=('species',))
session = ImportSession(args, "import-detail-sprites.py")
content = session.load()
clips = {}
for species in sorted(session.select('species', content['species'])):
    image = session.dist / f'assets/{species}-front.png'
    raw = image.read_bytes()
    if raw[:8] != b'\x89PNG\r\n\x1a\n':
        raise ValueError(f'Not a PNG: {image}')
    width, height = struct.unpack('>II', raw[16:24])
    if width != 64 or height % 64:
        raise ValueError(f'Expected 64px vertical frame sheet: {image}, {width}x{height}')
    clips[species] = height // 64
output = session.dist / 'packs/emerald/detail-sprite-frames.js'
session.text(output,'// @generated by tools/imports/commands/dex/import-detail-sprites.py; demonstration timing is defined by the pack.\n'
                  + 'export const DETAIL_SPRITE_FRAMES = Object.freeze('
                  + '{\n' + ''.join(f'  {key}: {count},\n' for key, count in clips.items()) + '});\n')
print(f'Detail frames: {len(clips)} species, {sum(n > 1 for n in clips.values())} animated sheets.')

session.finish()
